---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "issuer-node.fullname" . }}-svc
  labels:
    app.kubernetes.io/app: {{ include "issuer-node.fullname" . }}
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: {{ include "issuer-node.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ include "issuer-node.fullname" . }}
    app.kubernetes.io/managed-by: helm
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: {{ include "issuer-node.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ include "issuer-node.fullname" . }}
  ports:
    - name: ui-port
      port: {{ .Values.ui.port }}
      targetPort: {{ .Values.ui.port }}
      protocol: TCP
