import { useQuery } from "@tanstack/react-query";
import { AxiosError } from "axios";
import apiService from "./apiService";
import { SchemaType, Status } from "@/@types";

export type ResponseType = SchemaType[] | undefined;

const mockRegisterSchemaResponse: SchemaType[] = [
  {
    jsonLdCid: "QmX9k2z3w4V5u6Y7t8R9q0P1o2I3u4Y5t6R7e8W9q0A1s",
    vocabCid: "QmA1s2D3f4G5h6J7k8L9z0X1c2V3b4N5m6Q7w8E9r0T1y",
    jsonSchemaCid: "QmT1y2U3i4O5p6A7s8D9f0G1h2J3k4L5z6X7c8V9b0N1m",
    schemaType: "AcademicDegree",
    templateUrl: "https://templates.example.com/academic-degree/v1.0.json",
    createdAt: "2023-01-15T10:30:00.000Z",
    modifiedAt: "2023-08-20T14:45:00.000Z",
    schemaId: "schema_001",
    status: Status.ACTIVE,
    description:
      "Schema for academic degree certificates including bachelor's, master's, and doctoral degrees",
    issuers: [
      {
        companyLogo: "https://logos.university.edu/mit-logo.png",
        companyName: "Massachusetts Institute of Technology",
        id: "issuer_001",
      },
      {
        companyLogo: "https://logos.university.edu/stanford-logo.png",
        companyName: "Stanford University",
        id: "issuer_002",
      },
      {
        companyLogo: "https://logos.university.edu/harvard-logo.png",
        companyName: "Harvard University",
        id: "issuer_003",
      },
    ],
    schemaFields: [
      {
        key: "studentName",
        description: "Full name of the student receiving the degree",
        title: "Student Name",
        type: "string",
        descriptionAr: "الاسم الكامل للطالب الحاصل على الدرجة",
        titleAr: "اسم الطالب",
        required: true,
      },
      {
        key: "degreeTitle",
        description: "Title of the academic degree",
        title: "Degree Title",
        type: "string",
        descriptionAr: "عنوان الدرجة الأكاديمية",
        titleAr: "عنوان الدرجة",
        required: true,
      },
      {
        key: "major",
        description: "Field of study or major",
        title: "Major",
        type: "string",
        descriptionAr: "مجال الدراسة أو التخصص",
        titleAr: "التخصص",
        required: true,
      },
      {
        key: "gpa",
        description: "Grade Point Average",
        title: "GPA",
        type: "number",
        minimum: 0,
        descriptionAr: "المعدل التراكمي",
        titleAr: "المعدل",
        required: false,
      },
      {
        key: "graduationDate",
        description: "Date of graduation",
        title: "Graduation Date",
        type: "string",
        format: "date",
        descriptionAr: "تاريخ التخرج",
        titleAr: "تاريخ التخرج",
        required: true,
      },
    ],
  },
  {
    jsonLdCid: "QmB2t3E4r5T6y7U8i9O0p1A2s3D4f5G6h7J8k9L0z1X2c",
    vocabCid: "QmC3v4B5n6M7q8W9e0R1t2Y3u4I5o6P7a8S9d0F1g2H3j",
    jsonSchemaCid: "QmD4k5L6z7X8c9V0b1N2m3Q4w5E6r7T8y9U0i1O2p3A4s",
    schemaType: "ProfessionalCertification",
    templateUrl: "https://templates.example.com/professional-cert/v2.1.json",
    createdAt: "2023-02-20T09:15:00.000Z",
    modifiedAt: "2023-09-10T16:20:00.000Z",
    schemaId: "schema_002",
    status: Status.ACTIVE,
    description:
      "Schema for professional certifications from technology companies and training providers",
    issuers: [
      {
        companyLogo: "https://logos.tech.com/aws-logo.png",
        companyName: "Amazon Web Services",
        id: "issuer_004",
      },
      {
        companyLogo: "https://logos.tech.com/microsoft-logo.png",
        companyName: "Microsoft",
        id: "issuer_005",
      },
      {
        companyLogo: "https://logos.tech.com/google-logo.png",
        companyName: "Google",
        id: "issuer_006",
      },
      {
        companyLogo: "https://logos.tech.com/cisco-logo.png",
        companyName: "Cisco Systems",
        id: "issuer_007",
      },
    ],
    schemaFields: [
      {
        key: "candidateName",
        description: "Name of the certification candidate",
        title: "Candidate Name",
        type: "string",
        descriptionAr: "اسم مرشح الشهادة",
        titleAr: "اسم المرشح",
        required: true,
      },
      {
        key: "certificationTitle",
        description: "Title of the professional certification",
        title: "Certification Title",
        type: "string",
        descriptionAr: "عنوان الشهادة المهنية",
        titleAr: "عنوان الشهادة",
        required: true,
      },
      {
        key: "level",
        description: "Certification level (Associate, Professional, Expert)",
        title: "Level",
        type: "string",
        descriptionAr: "مستوى الشهادة (مشارك، محترف، خبير)",
        titleAr: "المستوى",
        required: true,
      },
      {
        key: "score",
        description: "Exam score or percentage",
        title: "Score",
        type: "number",
        minimum: 0,
        descriptionAr: "درجة الامتحان أو النسبة المئوية",
        titleAr: "النتيجة",
        required: false,
      },
      {
        key: "issueDate",
        description: "Date when certification was issued",
        title: "Issue Date",
        type: "string",
        format: "date",
        descriptionAr: "تاريخ إصدار الشهادة",
        titleAr: "تاريخ الإصدار",
        required: true,
      },
      {
        key: "expiryDate",
        description: "Date when certification expires",
        title: "Expiry Date",
        type: "string",
        format: "date",
        descriptionAr: "تاريخ انتهاء صلاحية الشهادة",
        titleAr: "تاريخ الانتهاء",
        required: false,
      },
    ],
  },
  {
    jsonLdCid: "QmE5f6G7h8J9k0L1z2X3c4V5b6N7m8Q9w0E1r2T3y4U5i",
    vocabCid: "QmF6o7P8a9S0d1F2g3H4j5K6l7Z8x9C0v1B2n3M4q5W6e",
    jsonSchemaCid: "QmG7r8T9y0U1i2O3p4A5s6D7f8G9h0J1k2L3z4X5c6V7b",
    schemaType: "SkillAssessment",
    templateUrl: "https://templates.example.com/skill-assessment/v1.5.json",
    createdAt: "2023-03-10T11:45:00.000Z",
    modifiedAt: "2023-10-05T13:30:00.000Z",
    schemaId: "schema_003",
    status: Status.ACTIVE,
    description:
      "Schema for skill-based assessments and competency evaluations",
    issuers: [
      {
        companyLogo: "https://logos.assessment.com/skillsoft-logo.png",
        companyName: "Skillsoft",
        id: "issuer_008",
      },
      {
        companyLogo: "https://logos.assessment.com/pluralsight-logo.png",
        companyName: "Pluralsight",
        id: "issuer_009",
      },
      {
        companyLogo: "https://logos.assessment.com/linkedin-logo.png",
        companyName: "LinkedIn Learning",
        id: "issuer_010",
      },
    ],
    schemaFields: [
      {
        key: "assesseeName",
        description: "Name of the person being assessed",
        title: "Assessee Name",
        type: "string",
        descriptionAr: "اسم الشخص الذي يتم تقييمه",
        titleAr: "اسم المُقيَّم",
        required: true,
      },
      {
        key: "skillArea",
        description: "Area or domain of the skill being assessed",
        title: "Skill Area",
        type: "string",
        descriptionAr: "مجال أو نطاق المهارة التي يتم تقييمها",
        titleAr: "مجال المهارة",
        required: true,
      },
      {
        key: "proficiencyLevel",
        description:
          "Level of proficiency (Beginner, Intermediate, Advanced, Expert)",
        title: "Proficiency Level",
        type: "string",
        descriptionAr: "مستوى الكفاءة (مبتدئ، متوسط، متقدم، خبير)",
        titleAr: "مستوى الكفاءة",
        required: true,
      },
      {
        key: "assessmentScore",
        description: "Numerical score from the assessment",
        title: "Assessment Score",
        type: "number",
        minimum: 0,
        descriptionAr: "النتيجة العددية من التقييم",
        titleAr: "نتيجة التقييم",
        required: true,
      },
      {
        key: "validFrom",
        description: "Date from which the assessment is valid",
        title: "Valid From",
        type: "string",
        format: "date",
        descriptionAr: "التاريخ الذي يصبح فيه التقييم صالحاً",
        titleAr: "صالح من",
        required: true,
      },
      {
        key: "validUntil",
        description: "Date until which the assessment remains valid",
        title: "Valid Until",
        type: "string",
        format: "date",
        descriptionAr: "التاريخ الذي يبقى فيه التقييم صالحاً",
        titleAr: "صالح حتى",
        required: false,
      },
    ],
  },
  {
    jsonLdCid: "QmH8i9O0p1A2s3D4f5G6h7J8k9L0z1X2c3V4b5N6m7Q8w",
    vocabCid: "QmI9e0R1t2Y3u4I5o6P7a8S9d0F1g2H3j4K5l6Z7x8C9v",
    jsonSchemaCid: "QmJ0b1N2m3Q4w5E6r7T8y9U0i1O2p3A4s5D6f7G8h9J0k",
    schemaType: "EmploymentRecord",
    templateUrl: "https://templates.example.com/employment/v1.2.json",
    createdAt: "2023-04-05T14:20:00.000Z",
    modifiedAt: "2023-11-15T10:10:00.000Z",
    schemaId: "schema_004",
    status: Status.DRAFT,
    description:
      "Schema for employment records and work experience verification",
    issuers: [
      {
        companyLogo: "https://logos.companies.com/techcorp-logo.png",
        companyName: "TechCorp Inc.",
        id: "issuer_011",
      },
      {
        companyLogo: "https://logos.companies.com/innovatesoft-logo.png",
        companyName: "InnovateSoft",
        id: "issuer_012",
      },
    ],
    schemaFields: [
      {
        key: "employeeName",
        description: "Full name of the employee",
        title: "Employee Name",
        type: "string",
        descriptionAr: "الاسم الكامل للموظف",
        titleAr: "اسم الموظف",
        required: true,
      },
      {
        key: "position",
        description: "Job title or position held",
        title: "Position",
        type: "string",
        descriptionAr: "المسمى الوظيفي أو المنصب",
        titleAr: "المنصب",
        required: true,
      },
      {
        key: "department",
        description: "Department or division",
        title: "Department",
        type: "string",
        descriptionAr: "القسم أو الشعبة",
        titleAr: "القسم",
        required: false,
      },
      {
        key: "startDate",
        description: "Employment start date",
        title: "Start Date",
        type: "string",
        format: "date",
        descriptionAr: "تاريخ بداية العمل",
        titleAr: "تاريخ البداية",
        required: true,
      },
      {
        key: "endDate",
        description: "Employment end date",
        title: "End Date",
        type: "string",
        format: "date",
        descriptionAr: "تاريخ نهاية العمل",
        titleAr: "تاريخ النهاية",
        required: false,
      },
      {
        key: "salary",
        description: "Salary or compensation amount",
        title: "Salary",
        type: "number",
        minimum: 0,
        descriptionAr: "الراتب أو مبلغ التعويض",
        titleAr: "الراتب",
        required: false,
      },
    ],
  },
  {
    jsonLdCid: "QmK1l2Z3x4C5v6B7n8M9q0W1e2R3t4Y5u6I7o8P9a0S1d",
    vocabCid: "QmL2f3G4h5J6k7L8z9X0c1V2b3N4m5Q6w7E8r9T0y1U2i",
    jsonSchemaCid: "QmM3o4P5a6S7d8F9g0H1j2K3l4Z5x6C7v8B9n0M1q2W3e",
    schemaType: "TrainingCompletion",
    templateUrl: "https://templates.example.com/training/v2.0.json",
    createdAt: "2023-05-12T16:00:00.000Z",
    modifiedAt: "2023-12-01T09:25:00.000Z",
    schemaId: "schema_005",
    status: Status.ACTIVE,
    description:
      "Schema for training course completion certificates and workshops",
    issuers: [
      {
        companyLogo: "https://logos.training.com/udemy-logo.png",
        companyName: "Udemy",
        id: "issuer_013",
      },
      {
        companyLogo: "https://logos.training.com/coursera-logo.png",
        companyName: "Coursera",
        id: "issuer_014",
      },
      {
        companyLogo: "https://logos.training.com/edx-logo.png",
        companyName: "edX",
        id: "issuer_015",
      },
    ],
    schemaFields: [
      {
        key: "participantName",
        description: "Name of the training participant",
        title: "Participant Name",
        type: "string",
        descriptionAr: "اسم المشارك في التدريب",
        titleAr: "اسم المشارك",
        required: true,
      },
      {
        key: "courseTitle",
        description: "Title of the training course",
        title: "Course Title",
        type: "string",
        descriptionAr: "عنوان الدورة التدريبية",
        titleAr: "عنوان الدورة",
        required: true,
      },
      {
        key: "duration",
        description: "Training duration in hours",
        title: "Duration (Hours)",
        type: "number",
        minimum: 1,
        descriptionAr: "مدة التدريب بالساعات",
        titleAr: "المدة (ساعات)",
        required: true,
      },
      {
        key: "completionDate",
        description: "Date when training was completed",
        title: "Completion Date",
        type: "string",
        format: "date",
        descriptionAr: "تاريخ إكمال التدريب",
        titleAr: "تاريخ الإنجاز",
        required: true,
      },
      {
        key: "grade",
        description: "Final grade or assessment result",
        title: "Grade",
        type: "string",
        descriptionAr: "الدرجة النهائية أو نتيجة التقييم",
        titleAr: "الدرجة",
        required: false,
      },
    ],
  },
  {
    jsonLdCid: "QmN4r5T6y7U8i9O0p1A2s3D4f5G6h7J8k9L0z1X2c3V4b",
    vocabCid: "QmO5n6M7q8W9e0R1t2Y3u4I5o6P7a8S9d0F1g2H3j4K5l",
    jsonSchemaCid: "QmP6z7X8c9V0b1N2m3Q4w5E6r7T8y9U0i1O2p3A4s5D6f",
    schemaType: "HealthCertificate",
    templateUrl: "https://templates.example.com/health/v1.1.json",
    createdAt: "2023-06-18T12:30:00.000Z",
    modifiedAt: "2023-06-18T12:30:00.000Z",
    schemaId: "schema_006",
    status: Status.PENDING,
    description:
      "Schema for health-related certifications and medical clearances",
    issuers: [
      {
        companyLogo: "https://logos.health.com/who-logo.png",
        companyName: "World Health Organization",
        id: "issuer_016",
      },
      {
        companyLogo: "https://logos.health.com/redcross-logo.png",
        companyName: "Red Cross",
        id: "issuer_017",
      },
    ],
    schemaFields: [
      {
        key: "patientName",
        description: "Name of the patient or certificate holder",
        title: "Patient Name",
        type: "string",
        descriptionAr: "اسم المريض أو حامل الشهادة",
        titleAr: "اسم المريض",
        required: true,
      },
      {
        key: "certificateType",
        description: "Type of health certificate",
        title: "Certificate Type",
        type: "string",
        descriptionAr: "نوع الشهادة الصحية",
        titleAr: "نوع الشهادة",
        required: true,
      },
      {
        key: "issuingDoctor",
        description: "Name of the issuing medical professional",
        title: "Issuing Doctor",
        type: "string",
        descriptionAr: "اسم الطبيب المُصدِر",
        titleAr: "الطبيب المُصدِر",
        required: true,
      },
      {
        key: "issueDate",
        description: "Date when certificate was issued",
        title: "Issue Date",
        type: "string",
        format: "date",
        descriptionAr: "تاريخ إصدار الشهادة",
        titleAr: "تاريخ الإصدار",
        required: true,
      },
      {
        key: "validityPeriod",
        description: "Validity period in months",
        title: "Validity Period (Months)",
        type: "number",
        minimum: 1,
        descriptionAr: "فترة الصلاحية بالأشهر",
        titleAr: "فترة الصلاحية (أشهر)",
        required: false,
      },
    ],
  },
  {
    jsonLdCid: "QmQ7g8H9j0K1l2Z3x4C5v6B7n8M9q0W1e2R3t4Y5u6I7o",
    vocabCid: "QmR8p9A0s1D2f3G4h5J6k7L8z9X0c1V2b3N4m5Q6w7E8r",
    jsonSchemaCid: "QmS9t0Y1u2I3o4P5a6S7d8F9g0H1j2K3l4Z5x6C7v8B9n",
    schemaType: "LicenseVerification",
    templateUrl: "https://templates.example.com/license/v1.3.json",
    createdAt: "2023-07-22T15:45:00.000Z",
    modifiedAt: "2023-10-30T11:20:00.000Z",
    schemaId: "schema_007",
    status: Status.INACTIVE,
    description:
      "Schema for professional licenses and regulatory certifications",
    issuers: [
      {
        companyLogo: "https://logos.gov.com/dmv-logo.png",
        companyName: "Department of Motor Vehicles",
        id: "issuer_018",
      },
      {
        companyLogo: "https://logos.professional.com/bar-association-logo.png",
        companyName: "State Bar Association",
        id: "issuer_019",
      },
    ],
    schemaFields: [
      {
        key: "licenseHolderName",
        description: "Name of the license holder",
        title: "License Holder Name",
        type: "string",
        descriptionAr: "اسم حامل الرخصة",
        titleAr: "اسم حامل الرخصة",
        required: true,
      },
      {
        key: "licenseType",
        description: "Type of professional license",
        title: "License Type",
        type: "string",
        descriptionAr: "نوع الرخصة المهنية",
        titleAr: "نوع الرخصة",
        required: true,
      },
      {
        key: "licenseNumber",
        description: "Unique license identification number",
        title: "License Number",
        type: "string",
        pattern: "^[A-Z0-9]{6,12}$",
        descriptionAr: "رقم تعريف الرخصة الفريد",
        titleAr: "رقم الرخصة",
        required: true,
      },
      {
        key: "issueDate",
        description: "Date when license was first issued",
        title: "Issue Date",
        type: "string",
        format: "date",
        descriptionAr: "تاريخ أول إصدار للرخصة",
        titleAr: "تاريخ الإصدار",
        required: true,
      },
      {
        key: "expirationDate",
        description: "Date when license expires",
        title: "Expiration Date",
        type: "string",
        format: "date",
        descriptionAr: "تاريخ انتهاء صلاحية الرخصة",
        titleAr: "تاريخ الانتهاء",
        required: true,
      },
      {
        key: "restrictions",
        description: "Any restrictions or conditions on the license",
        title: "Restrictions",
        type: "string",
        descriptionAr: "أي قيود أو شروط على الرخصة",
        titleAr: "القيود",
        required: false,
      },
    ],
  },
];

const useGetRegisterSchema = () => {
  return useQuery<ResponseType, AxiosError>({
    queryKey: ["register-schema"],
    queryFn: async () => {
      // const { data } = await apiService().get("/v1/register-schemas/get-all");
      // return data;
      return mockRegisterSchemaResponse;
    },
  });
};

export default useGetRegisterSchema;
