name: Caches Cleanup By A Branch
on:
  pull_request:
    types: ['closed']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main'  }}

jobs:
  cleanup:
    runs-on: shared-services-platform
    steps:
      - id: checkout
        name: Checkout the codebase
        uses: actions/checkout@v3.6.0

      - id: install-gh-cli
        name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@master
        with:
          gh-cli-version: 2.33.0
      
      - id: cleanup-cache
        name: Cleanup Github Action cache
        run: |
          gh extension install actions/gh-actions-cache
          
          REPO=${{ github.repository }}
          BRANCH="refs/pull/${{ github.event.pull_request.number }}/merge"

          echo "Fetching list of cache key"
          cacheKeysForPR=$(gh actions-cache list -R $REPO -B $BRANCH -L 100 | cut -f 1 )

          ## Setting this to not fail the workflow while deleting cache keys. 
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForPR
          do
              gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
