---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "issuer-node.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/app: {{ include "issuer-node.fullname" . }}
    app.kubernetes.io/component: {{ include "issuer-node.fullname" . }}
    app.kubernetes.io/part-of: {{ include "issuer-node.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: {{ include "issuer-node.fullname" . }}
      app.kubernetes.io/component: {{ include "issuer-node.fullname" . }}
      app.kubernetes.io/part-of: {{ include "issuer-node.fullname" . }}
      app.kubernetes.io/namespace: {{ .Release.Namespace }}
      app.kubernetes.io/release: {{ .Release.Name }}
      app.kubernetes.io/managed-by: helm
  template:
    metadata:
      labels:
        app.kubernetes.io/app: {{ include "issuer-node.fullname" . }}
        app.kubernetes.io/component: {{ include "issuer-node.fullname" . }}
        app.kubernetes.io/part-of: {{ include "issuer-node.fullname" . }}
        app.kubernetes.io/namespace: {{ .Release.Namespace }}
        app.kubernetes.io/release: {{ .Release.Name }}
        app.kubernetes.io/managed-by: helm
    spec:
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}  
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      containers:
      - name: {{ include "issuer-node.fullname" . }}
        image: {{ .Values.image.issuer.repository }}:{{ .Values.image.issuer.tag }}
        imagePullPolicy: {{ .Values.image.issuer.pullPolicy }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
          - name: ui-port
            containerPort: {{ .Values.ui.port }}
            protocol: TCP
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.lifecycle }}
        lifecycle:
          {{- toYaml . | nindent 10 }}
        {{- end }}
